#!/usr/bin/env python3
"""Generate Latveria Refinement v3 - the fourth, purely additive command layer.

    python build_refinement.py     -> ../windows/latveria_refinement_v3_commands.txt
                                      ../docs/v3/build_report.json

Needs numpy.  Models the world left by the three executed layers (main build, Survival
Expansion v2, Lighting Overhaul) and writes only guarded commands (see v3core.py).
Every section is independent and safe to re-run.
"""
import json
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import build as build1
import sim
from core import chat_len, CHAT_LIMIT, GenError, tc
from v3core import V3

import v3_golem
import v3_castle
import v3_secrets
import v3_city
import v3_districts

WIN = os.path.join(HERE, "..", "windows")
EXECUTED = ["latveria_commands.txt", "latveria_expansion_commands.txt", "latveria_lighting_commands.txt"]
OUT = os.path.join(WIN, "latveria_refinement_v3_commands.txt")
REPORT = os.path.join(HERE, "..", "docs", "v3", "build_report.json")

# section order: the mandatory farm fix first, then Castle Doom, then the city and districts
MODULES = [v3_golem, v3_castle, v3_secrets, v3_city, v3_districts]


def base_world():
    w = sim.World()
    for f in EXECUTED:
        w.load_file(os.path.join(WIN, f))
    return w


def main():
    t0 = time.time()
    w = base_world()
    n_ent0 = len(w.entities)
    v = V3(w)
    v.w0 = base_world()
    for m in MODULES:
        m.build(v)
    v.close_section()
    v.b.section("finish", "Finishing")
    v.sec = "finish"
    v.b.raw('title @s subtitle %s' % tc("Latveria endures - refined, not rebuilt", "gray", italic=True))
    v.b.raw('title @s title %s' % tc("LATVERIA", "dark_green", bold=True))
    n = write(v)
    write_reset(w)
    rep = {
        "commands": n,
        "sections": [s["title"] for s in v.b.sections
                     if any(not t.startswith(("!wait", "tp @s ", "title @s actionbar")) for t, _ in s["cmds"])],
        "structural_problems": v.problems,
        "stats": dict(v.stats),
        "skipped_pieces": v.skipped,
        "mechanisms": v.mechanisms,
        "entities_before": n_ent0,
        "entities_after": len(w.entities),
        "generator_seconds": round(time.time() - t0, 1),
    }
    os.makedirs(os.path.dirname(REPORT), exist_ok=True)
    with open(REPORT, "w") as f:
        json.dump(rep, f, indent=1)
    print("problems: %d   pieces: %d built, %d skipped   entities %d -> %d" % (
        len(v.problems), v.stats["pieces"], v.stats["pieces_skipped"], n_ent0, len(w.entities)))
    for p in v.problems[:40]:
        print("  PROBLEM", p)
    return 1 if v.problems else 0


RESET = os.path.join(WIN, "latveria_v3_nursery_reset_commands.txt")


def write_reset(world):
    """The optional nursery bed reset, as its own small file (run it when you want more children)."""
    r = V3(world)
    v3_districts.nursery_reset(r)
    save(r, RESET, "Latveria v3 - nursery bed reset (optional; run after Refinement v3 whenever wanted)")


def write(v):
    return save(v, OUT, "Latveria Refinement v3 - generated by generator/build_refinement.py")


def save(v, path, title):
    lines = []
    n = 0
    ymin, ymax = 0, 0
    for sec in v.b.sections:
        work = [t for t, _ in sec["cmds"] if not t.startswith(("!wait", "tp @s ", "title @s actionbar"))]
        if not work:
            continue                      # nothing to build here: no teleport, no wait
        lines.append("!section\t%s" % sec["title"])
        for text, cost in sec["cmds"]:
            if text.startswith("!wait"):
                _, ms, note = text.split(" ", 2)
                lines.append("!wait\t%s\t%s" % (ms, note))
                continue
            if chat_len(text) > CHAT_LIMIT:
                raise GenError("too long: " + text)
            for yv in re.findall(r"\$y\((-?[0-9.]+)\)", text):
                ymin = min(ymin, float(yv)); ymax = max(ymax, float(yv))
            lines.append("%d\t%s" % (build1.weight(text, cost), text))
            n += 1
    with open(path, "w", newline="\r\n") as f:
        f.write("# %s - %d commands\n" % (title, n))
        f.write("# Additive layer: run AFTER latveria_commands, latveria_expansion and latveria_lighting.\n")
        f.write("# mode additive\n")
        f.write("# range y %d %d\n" % (int(ymin) - 1, int(ymax) + 1))
        f.write("\n".join(lines) + "\n")
    print("commands: %d   wrote %s" % (n, os.path.normpath(path)))
    return n


if __name__ == "__main__":
    sys.exit(main())
