#!/usr/bin/env python3
"""Generate the Latveria Lighting Overhaul as a third chat-command file.

    python build_lighting.py      -> ../windows/latveria_lighting_commands.txt

Needs numpy.  Models the world left by latveria_commands.txt and
latveria_expansion_commands.txt, so generate those first.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from core import Builder, tc, GenError, chat_len, CHAT_LIMIT
import build as build1
import build_expansion as bx
import lighting as LG
import sim

WIN = os.path.join(HERE, "..", "windows")
FILES = [os.path.join(WIN, "latveria_commands.txt"), os.path.join(WIN, "latveria_expansion_commands.txt")]
OUT = os.path.join(WIN, "latveria_lighting_commands.txt")

CASTLE = (-62, 1, -222, 62, 115, -100)
TOWN = (-143, -26, -70, 143, 60, 103)
TUNNEL = (-44, -12, -168, -2, 6, -58)
EAST = (151, -1, -130, 300, 44, 112)
SOUTH = (-150, -6, 113, 150, 40, 240)
WEST = (-300, -1, -130, -151, 40, 112)
EAST_EXCL = [(230, -1, -47, 281, 34, -28), (241, -1, -101, 264, 14, -78), (228, -140, 28, 300, -2, 92)]


def main():
    world = sim.World()
    for f in FILES:
        world.load_file(f)
    b = Builder()
    L = LG.Lighter(b, world, LG.frame_supports(FILES))

    b.section("setup", "Preparing the lighting overhaul")
    b.raw("gamerule send_command_feedback false")
    b.raw("gamerule log_admin_commands false")
    for q in build1.QUADS:
        b.raw("forceload add %s %s %s %s" % (bx.cx(q[0]), bx.cz(q[1]), bx.cx(q[2]), bx.cz(q[3])))
    b.wait(60000, "loading the castle and town")

    LG.designed_castle(L)
    n0 = L.count
    LG.light_pass(L, CASTLE, "Castle Doom", exclude=[LG.FACTORY])
    print("castle: %d designed, %d total" % (n0, L.count))
    LG.light_pass(L, TUNNEL, "the escape tunnel")
    n1 = L.count
    LG.light_pass(L, TOWN, "Doomstadt")
    print("town: %d" % (L.count - n1))

    for (quads, box, name, excl) in ((bx.EAST_Q, EAST, "Doomwerk", EAST_EXCL), (bx.SOUTH_Q, SOUTH, "the Southmarch", []),
                                     (bx.WEST_Q, WEST, "the West March", [])):
        b.section("load_" + name, "Loading " + name)
        for q in quads:
            b.raw("forceload add %s %s %s %s" % (bx.cx(q[0]), bx.cz(q[1]), bx.cx(q[2]), bx.cz(q[3])))
        b.wait(45000, "loading " + name)
        n = L.count
        LG.light_pass(L, box, name, exclude=excl)
        print("%s: %d" % (name, L.count - n))
        for q in quads:
            b.raw("forceload remove %s %s %s %s" % (bx.cx(q[0]), bx.cz(q[1]), bx.cx(q[2]), bx.cz(q[3])))

    # streets and plaza last, while the town is still loaded
    b.section("reload_town", "Back to the town")
    LG.designed_town(L)

    b.section("finish", "Finishing")
    for q in build1.QUADS:
        b.raw("forceload remove %s %s %s %s" % (bx.cx(q[0]), bx.cz(q[1]), bx.cx(q[2]), bx.cz(q[3])))
    b.raw("gamerule log_admin_commands true")
    b.raw("gamerule send_command_feedback true")
    b.raw('title @s subtitle {text:"Every hall of Latveria now shines",color:"gray",italic:1b}')
    b.raw('title @s title {text:"LET THERE BE DOOM",color:"dark_green",bold:1b}')
    print("total light changes: %d" % L.count)
    write(b)


def write(b):
    lines = []
    n = 0
    ymin, ymax = 0, 0
    for sec in b.sections:
        if not sec["cmds"]:
            continue
        lines.append("!section\t%s" % sec["title"])
        lines.append("0\ttitle @s actionbar %s" % tc("Lighting: " + sec["title"], "green"))
        for text, cost in sec["cmds"]:
            if text.startswith("!wait"):
                _, ms, note = text.split(" ", 2)
                lines.append("!wait\t%s\t%s" % (ms, note))
                continue
            if chat_len(text) > CHAT_LIMIT:
                raise GenError("too long: " + text)
            for yv in re.findall(r"\$y\((-?[0-9.]+)\)", text):
                ymin = min(ymin, float(yv)); ymax = max(ymax, float(yv))
            lines.append("%d\t%s" % (build1.weight(text, cost), text))
            n += 1
    with open(OUT, "w", newline="\r\n") as f:
        f.write("# Latveria Lighting Overhaul - generated by generator/build_lighting.py - %d commands\n" % n)
        f.write("# range y %d %d\n" % (int(ymin) - 1, int(ymax) + 1))
        f.write("\n".join(lines) + "\n")
    print("commands: %d   wrote %s" % (n, os.path.normpath(OUT)))


if __name__ == "__main__":
    main()
