#!/usr/bin/env python3
"""Write docs/v3/VERIFICATION_REPORT.md from verification.json and build_report.json (run verify3.py first)."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, "..", "docs", "v3")
CENTRE = (799, 70, -10090)


def main():
    v = json.load(open(os.path.join(D, "verification.json")))
    b = json.load(open(os.path.join(D, "build_report.json")))
    lo = v["changed_bounds_rel"]
    ab = [lo[0] + CENTRE[0], lo[1] + CENTRE[1], lo[2] + CENTRE[2], lo[3] + CENTRE[0], lo[4] + CENTRE[1], lo[5] + CENTRE[2]]
    g = v["golem_works"]
    L = []
    L.append("# Refinement v3 - verification report\n")
    L.append("Generated by `generator/report3.py` from `verify3.py` and `build_refinement.py` output. Every figure below "
             "comes from the voxel model of the world after replaying the three executed layers and then v3. "
             "**Nothing here was run in Minecraft.**\n")
    L.append("| Check | Result |\n|---|---|")
    rows = [
        ("Structural problems (verifier)", "**%d**" % len(v["structural_problems"])),
        ("Structural problems (generator)", "**%d**" % len(b["structural_problems"])),
        ("Commands", "%d in %d sections" % (v["commands"], len(b["sections"]))),
        ("Longest command", "%d characters (limit 256, coordinates counted at 8 characters)" % v["longest_command_chars"]),
        ("Non-air blocks before / after", "%s / %s" % (format(v["non_air_blocks_before"], ","), format(v["non_air_blocks_after"], ","))),
        ("Cells changed by v3", format(v["cells_changed_by_v3"], ",")),
        ("Changed bounds (relative)", "x %d..%d, y %d..%d, z %d..%d" % (lo[0], lo[3], lo[1], lo[4], lo[2], lo[5])),
        ("Changed bounds (absolute, centre 799 70 -10090)", "x %d..%d, y %d..%d, z %d..%d" % (ab[0], ab[3], ab[1], ab[4], ab[2], ab[5])),
        ("Min / max y written (relative)", "%d / %d" % tuple(v["y_range_rel"])),
        ("Entities before / after", "%d / %d" % (v["entities_before"], v["entities_after"])),
        ("New v3 entities", ", ".join("%d %s" % (n, t) for t, n in v["v3_entities"].items())),
        ("Replacement operations (fill ... replace)", str(v["command_kinds"].get("fill replace", 0))),
        ("Placements into air (setblock/fill keep)", "%d / %d" % (v["command_kinds"].get("setblock keep", 0), v["command_kinds"].get("fill keep", 0))),
        ("Guarded summons / container fills / two-part blocks", "%d / %d / %d" % (
            v["command_kinds"].get("guarded summon", 0), v["command_kinds"].get("guarded container item", 0),
            v["command_kinds"].get("guarded two-part block", 0))),
        ("Idempotency (second full replay)", "%d blocks changed, %d entities added" % (
            v["idempotency"]["blocks_changed_on_second_replay"], v["idempotency"]["entities_added_on_second_replay"])),
        ("Player's Doombot factory room", "unchanged (0 cells)"),
        ("Supports checked (cells v3 placed or touched)", format(v["support_cells_checked"], ",")),
        ("New dark spawnable cells where v3 built", "%d (over %d 32x32 tiles)" % (v["new_dark_cells"]["new_dark_spawnable_cells"], v["new_dark_cells"]["tiles_checked"])),
        ("Hall of Shadows", "%d cells at block light 0 before; %d lit by v3" % (
            v["darkness"]["Hall of Shadows dark cells before"], v["darkness"]["Hall of Shadows dark cells lit by v3"])),
        ("New rooms, dark spawnable cells", ", ".join("%s %d" % (k.replace("dark spawnable cells in ", ""), n)
                                                      for k, n in v["darkness"].items() if k.startswith("dark spawnable"))),
        ("Gamerule / forceload / kill commands", "0"),
        ("Lights added by the relight rule", str(b["stats"].get("lights", 0))),
        ("Decorations left out whole (occupied in model)", str(b["stats"].get("pieces_skipped", 0))),
        ("Single guarded blocks left out (occupied in model)", str(b["stats"].get("singles_skipped", 0))),
    ]
    for k, r in rows:
        L.append("| %s | %s |" % (k, r))
    L.append("\n## Golem Works simulation\n")
    L.append("Every spawn attempt a villager in any of the 8 pod cells can make (17x17 offsets, top-down scan from +6 to -7) "
             "was evaluated with the legacy iron-golem rules (spawn cell air or liquid; block below solid-render and not "
             "glass/sea lantern/glowstone/leaves/...; the two cells above free).\n")
    L.append("| Outcome | Attempts |\n|---|---|")
    for k, n in g["spawn attempts (villager cell x offset)"].items():
        L.append("| %s | %d |" % (k, n))
    L.append("\n* Rim water sources: %d of 68; pad cells beyond water reach: %d" % (g["rim water sources"], g["pad cells beyond water reach"]))
    L.append("* Partition x=255 (y,z -> block): %s" % ", ".join("%s %s" % (k, n) for k, n in g["partition"].items()))
    L.append("* Pod floors: %s; beds: %d; crew: %s" % (", ".join(g["pod floors"]), g["beds"], ", ".join(g["crew"])))
    L.append("* Iron golems within 40 blocks of the farm: %d" % g["iron golems within 40 blocks"])
    L.append("\n## Mechanisms\n")
    L.append("| Mechanism | Status | How it works |\n|---|---|---|")
    for sec, name, status, text in b["mechanisms"]:
        L.append("| %s | %s | %s |" % (name, status, text))
    m = v["mechanisms"]
    L.append("\nState checks: Time Platform lamps on the chain: %d/7; sorter modules complete: %d/6; "
             "Children's Yard floor at y %s." % (m["time chain lamps"], m["sorter modules complete"], m["children's yard floor y"]))
    L.append("\n## Farm and test status\n")
    L.append("* **Structurally verified**: placements, supports, protected volume, idempotency, darkness, entity positions, "
             "command hygiene, the Foundry wiring, the gate batteries' manual triggers.")
    L.append("* **Mechanically reasoned (and, for the Golem Works, simulated)**: Golem Works cycle, night shutter, throne "
             "hatch, Time Platform chain, Sorting Office filters, nursery exit.")
    L.append("* **Requires a live Minecraft test**: all of the above mechanisms. No farm is claimed to be proven functional.")
    L.append("\n## Longest command\n\n```\n%s\n```" % v["longest_command"])
    L.append("\n## Sections\n")
    for i, s in enumerate(b["sections"]):
        L.append("%d. %s" % (i + 1, s))
    open(os.path.join(D, "VERIFICATION_REPORT.md"), "w").write("\n".join(L) + "\n")
    print("wrote VERIFICATION_REPORT.md")


if __name__ == "__main__":
    main()
